# Generated by Django 5.2.15 on 2026-06-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_image_profile_image_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'پیش نویس'), ('PB', 'منتشر شده'), ('RV', 'در انتظار بررسی')], max_length=2),
        ),
    ]
